name: "Feature Request"
description: Suggest a new feature or improvement
labels: [feature]
body:
  - type: markdown
    attributes:
    value: |
      Thanks for suggesting an idea to improve OnePointHub!

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? Who is it for?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you have in mind.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?

  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: This should be a new module
        - label: This extends an existing module
        - label: This affects the core platform

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, screenshots, or references
